name: andrewhobgood.com
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3064516
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d4e0'
    - '#000000'
    - '#323f6b'
    - '#88aacf'
    - '#996663'
  brandStrength: 0.9974636
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
